### ISSUE TITLE
rename `pick_reference_otus`?

### ISSUE THREAD

**Issue by gregcaporaso** [knights-lab/q2-ninja-ops#2]
I'm wondering if it'd make sense to call this `pick_closed_reference_otus`, so it's clearly differentiated from open-reference OTU picking, and so that it aligns with the name of the method in QIIME 1 (which will make it easier for users coming from Q1).

**Comment by bhillmann** [comment]
Ok, I updated the registered function name to ```pick_closed_reference_otus```.
